#ifndef LIBCOMMUNICATE_GLOBAL_H
#define LIBCOMMUNICATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBCOMMUNICATE_LIBRARY)
#  define LIBCOMMUNICATE_EXPORT Q_DECL_EXPORT
#else
#  define LIBCOMMUNICATE_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBCOMMUNICATE_GLOBAL_H
